# Generated by Django 4.0.3 on 2022-04-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(max_length=30)),
                ('lastUpdateTime', models.DateTimeField(verbose_name='updated Time')),
                ('itemsLastWeek', models.CharField(max_length=30)),
                ('itemsComingWeek', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=60)),
                ('shirt_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
            ],
        ),
    ]
