# Generated by Django 4.0.3 on 2022-04-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyReport', '0002_report_week_report_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='others',
            field=models.CharField(default='N.A.', max_length=120),
            preserve_default=False,
        ),
    ]
