# Generated by Django 4.0.3 on 2022-04-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyReport', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='customer',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
