# Generated by Django 4.0.3 on 2022-04-10 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyReport', '0005_task_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='建立時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
    ]
