# Generated by Django 4.0.3 on 2022-04-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyReport', '0006_task_create_time_task_update_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('customer_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=120)),
                ('ranking', models.IntegerField()),
            ],
        ),
    ]
