# Generated by Django 3.2.5 on 2022-04-14 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ClockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=24)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announce_name', models.CharField(max_length=30)),
                ('file_name', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('description', models.CharField(max_length=120, verbose_name='說明')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announce.category_announcement')),
            ],
        ),
    ]
