# Generated by Django 3.2.5 on 2022-04-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='uploader',
            field=models.CharField(default='hodgepai', max_length=20),
            preserve_default=False,
        ),
    ]
