# Generated by Django 4.0.3 on 2022-04-16 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0002_announcement_uploader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement_Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announce_name', models.CharField(max_length=30)),
                ('file_name', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('description', models.CharField(max_length=120, verbose_name='說明')),
                ('uploader', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announce.category_benefits')),
            ],
        ),
    ]
